### ISSUE TITLE
sbt run not working

### ISSUE THREAD

**Issue by alexandrmiee** [shmishleniy/sbt-deploy-ssh#14] opened 2019-03-08 05:24 UTC
After added in built.sbt file

```
import deployssh.DeploySSH._
import fr.janalyse.ssh.SSH
lazy val myProject = project.in(file(".")).settings(
	deployConfigs ++= Seq(
		ServerConfig("dev", "***.***.***.***",Option("******"),Option("*********"))
	),
	deployArtifacts ++= Seq(
		ArtifactSSH((packageBin in Universal).value, "/dep-test/")
	),
	deploySshExecAfter ++= Seq(
		(ssh: SSH) => {
			ssh.execOnce("cd /dep-test/")
			ssh.execOnce("unzip backend-1.0.zip")
		}
	)
).enablePlugins(DeploySSH)
```

sbt run not working

```
sbt:backend> run
[error] java.lang.RuntimeException: No main class detected.
[error]         at scala.sys.package$.error(package.scala:26)
[error] (Compile / bgRun) No main class detected.
[error] Total time: 2 s, completed 08.03.2019 8:21:33
sbt:backend>
```

**Comment by tellnobody1** [comment] 2019-03-08 09:11
`run` looking for App or main methods in your code. It has nothing common with deploy.
Use `deploySsh dev` command.

**Comment by tellnobody1** [comment] 2019-03-08 09:23
Cannot reproduce. Closing.

By the way your code doesn't work. You need to add `enablePlugins(JavaAppPackaging, DeploySSH)`. Then add anywhere in source code:
```object A extends App {}```

In `project/build.sbt`:

```
addSbtPlugin("com.github.shmishleniy" % "sbt-deploy-ssh" % "0.1.4")
resolvers += "JAnalyse Repository" at "http://www.janalyse.fr/repository/"
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.14")
```

Then running `run` will show:

```
sbt:myProject> run
[info] Compiling 1 Scala source to target/scala-2.12/classes ...
[info] Done compiling.
[info] Packaging test/target/scala-2.12/myproject_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Running A
[success] Total time: 3 s, completed Mar 8, 2019 11:19:36 AM
```

Also, it is not clear where is project `backend` where you want to execute `run`

**Closed as completed by tellnobody1** 2019-03-08 09:23 UTC
